version: "3.0"

networks:
  app:
    driver: bridge

volumes:
  db-data:
    driver: local

services:

  postgres:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgres/data
    networks:
      - app
    environment:
      - POSTGRES_DB=processing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
